# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'agenda' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # pod 'React', :path => '../node_modules/react-native'
  # pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'Firebase/Core', '~> 5.20.1'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  # pod 'Firebase/Core', '~> 5.20.1'
  # pod 'Firebase/Database', '~> 5.20.1'
  # pod 'Firebase/Functions', '~> 5.20.1'
  # pod 'Firebase/DynamicLinks', '~> 5.20.1'
  # pod 'Firebase/Firestore', '~> 5.20.1'
  # # pod 'Firebase/Invites', '~> 5.20.1'
  # pod 'Firebase/Messaging', '~> 5.20.1'
  # pod 'Firebase/RemoteConfig', '~> 5.20.1'
  # pod 'Firebase/Storage', '~> 5.20.1'
  # pod 'Firebase/Performance', '~> 5.20.1'
  # pod 'Fabric', '~> 1.9.0'
  # pod 'Crashlytics', '~> 3.12.0'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
